---

- block:
    - name: Update package information
      apt:
        update_cache: yes

    - name: install openjdk-8-jdk
      apt:
        name: "{{packages}}"
        update_cache: no
        install_recommends: no
      vars:
        packages:
          - openjdk-8-jdk

  when:
    - ansible_distribution == "Ubuntu"
  become: yes


