---

- block:
    - name: Install Beyond-Compare version 4.3.7
      apt:
        deb: "https://www.scootersoftware.com/bcompare-4.4.1.26165_amd64.deb"

  become: yes
  when:
    - ansible_distribution == "Ubuntu"
