---

- block:
    - name: remove weak host key
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^HostKey.*/etc/ssh/ssh_host_dsa_key"
        state: absent
      notify: sshd-restart

    - name: disable weak cryptographic algorithms
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^{{item.key}}\b'
        line: "{{item.key}} {{item.value}}"
      notify: sshd-restart
      with_items:
        - key: 'KexAlgorithms'
          value: 'curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256'
        - key: 'Ciphers'
          value: 'chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
        - key: 'MACs'
          value: 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com'

  become: yes
