---

- block:
  - name: get enable status
    command: debconf-show unattended-upgrades
    changed_when: false
    register: ua_enable_result

  - name: pre-seed enable switch
    debconf:
      name: unattended-upgrades
      question: unattended-upgrades/enable_auto_updates
      vtype: boolean
      value: "true"
    changed_when: false

  - name: install unattended upgrades to increase security
    apt:
      name: "unattended-upgrades"
      state: present
      update_cache: no
    register: ua_install_result

  - name: create periodic upgrade configuration
    command: '/usr/sbin/dpkg-reconfigure --frontend noninteractive unattended-upgrades'
    when:
      -  ua_enable_result.stdout is not search('enable_auto_updates' ~ ':' ~ ' true')
      -  ua_install_result is not changed

  - name: Creating override timer for unattended upgrades
    file:
      path: /etc/systemd/system/apt-daily-upgrade.timer.d
      state: directory

  - name: Creating override config file for unattended upgrades
    copy:
      src: files/override.conf
      dest: '/etc/systemd/system/apt-daily-upgrade.timer.d'
      owner: root
      group: root
      mode: 0644
    notify: configureUpdates

  - name: make update process interruptible
    lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '^Unattended-Upgrade::MinimalSteps'
      line: 'Unattended-Upgrade::MinimalSteps "true";'
      insertafter: '//.*MinimalSteps.*'

  - name: Add a dpkg.cfg options causing non-interactive upgrades
    lineinfile:
      path: /etc/dpkg/dpkg.cfg
      line: force-confold

  become: yes
