---

- hosts: standard
  force_handlers: true
  roles:
    - basic-hostname
    - basic-users
    - basic-repo
    - basic-proxy
    - basic-unattended-upgrades
    - basic-certificates
    - basic-nfs
    - basic-nss-certs
    - basic-ntp
    - basic-ssh
    - basic-GRUB-security
    - basic-antivirus
    - basic-equipment
    - basic-nvidia-driver
    - basic-upgrade

- hosts: rnd
  force_handlers: true
  roles:
    - advanced-rnd
    - advanced-git
    - advanced-sumo

- hosts: java_developer
  force_handlers: true
  roles:
    - advanced-java-env
    - advanced-vscode
    - advanced-beyond-compare

- hosts: azure_developer
  force_handlers: true
  roles:
    - advanced-azure-cli
    - advanced-vscode
    - advanced-beyond-compare
