---

- hosts: standard
  force_handlers: true
  roles:
    - basic-repo
    - basic-proxy
    - basic-unattended-upgrades
    - basic-certificates
    - basic-nfs
    - basic-nss-certs
    - basic-ntp
    - basic-ssh
    - basic-GRUB-security
    - basic-antivirus
