---

- block:
    - name: install prerequitite packages
      apt:
        name: pciutils
        update_cache: no

    - name: check nvidia GPU presence
      shell: |
        lspci -d {{nvidia}}::0300 -n
        lspci -d {{nvidia}}::0302 -n
        lspci -d {{nvidia}}::0604 -n
      changed_when: false
      register: nvidia_pci

    - block:
        - name: ensure /usr/lib/nvidia exists
          file:
            path: /usr/lib/nvidia
            state: directory
            owner: root
            group: root
            mode: 0755

        - name: install nvidia driver
          apt:
            name: "nvidia-driver-450"
            state: present
            update_cache: no
      when:
        - nvidia_pci.stdout is search(nvidia ~ ":")

  when:
    - ansible_distribution == "Ubuntu"
  become: yes
